### ISSUE TITLE
sources do not load get 404 error.

### ISSUE THREAD

**Issue by cdmvirt** [ReallyFuzzy/IceFilms.Bundle#1]
Hey,
Great plugin, I tried the new beta and love it, but as of late, the source pages for any TV show/movie returns a 404 error. As you have not had any activity on PLEX forums I was hoping I could catch you on here. I know life comes first and understand, but could you drop a line to many fans of this wonderful plugin. Also so you know if you dont already both your plugins (lmwt and icefilms) no longer work with new Samsung PLEX app because of missing -audioCodec tag is missing.

Again thanks, and hopefully hear from you soon.

**Comment by alexcarruthers** [comment]
It seems to be a parsing error in the GetSources method of the Parser.py file.  https://forums.plex.tv/index.php/topic/23049-icefilms/page-17

**Comment by cdmvirt** [comment]
I noticed that, but because i dont know how the parsing is done, I dont have the coding expertise to fix it... it driving me crazy... that and the -audioCodec tag needs to be add somewhere to get it to work on Samsung TV app.
